name:                amortia
version:             0.1.0.0
github:              "laluxx/amortia"
license:             MIT
author:              "Laluxx"
maintainer:          "lorenzoaddamo10@gmail.com"
copyright:           "2024 Laluxx"

extra-source-files:
- README.md
- LICENSE
- visualizer.html
- logo.svg

description:         Amortia programming language compiler

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec
- parser-combinators
- process
- filepath
- aeson
- directory
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: .
  exposed-modules:
  - Parser
  - Codegen
  - Visualizer

executables:
  amortia:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - amortia
