name:                amortia
version:             0.1.0.0
github:              "laluxx/amortia"
license:             MIT
author:              "Laluxx"
maintainer:          "lorenzoaddamo10@gmail.com"
copyright:           "2024 Laluxx"

extra-source-files:
- README.md
- LICENSE
- visualizer.html
- logo.svg

description:         Amortia programming language compiler

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec
- parser-combinators
- process
- filepath
- aeson
- directory
- time
- fsnotify
- lsp >= 2.0
- lsp-types >= 2.0
- lens

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

# Build only executables for faster compilation
executables:
  amortia:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    other-modules:
    - Parser
    - Codegen
    - Visualizer
    - Lsp
  
  # Separate LSP server executable
  amortia-lsp:
    main:                MainLsp.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    other-modules:
    - Parser
    - Lsp
